[Aswath][#4] Add. Basic github actions to run tests and lint
gopinathr143/go-collections pull request #8
Opened 2023-04-28 09:58 UTC by aswath-s-tw

2023-04-30 08:44 UTC, adarsh-a-tw requested changes

2023-04-30 08:44 UTC, adarsh-a-tw commented on main.go
Can we remove main.go as our package doesn't require this ?
@aswath-s-tw @gopinathr143

2023-05-12 04:55 UTC, gopinathr143 commented on main.go
Sure it is not needed since we have covered with test cases. Thank you

2023-05-15 16:38 UTC, aswath-s-tw commented on main.go
Removed `main.go` on the latest commit !

2023-05-16 09:07 UTC, adarsh-a-tw approved these changes

2023-05-16 09:07 UTC, merged